### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by concon121** [jacob-meacham/serverless-plugin-deploy-environment#5]
Looks like babel is not transforming to nodes require() syntax.  I'm not too familiar with Babel, tried a few things locally but cant get it to work.

```
SyntaxError: Unexpected token import
/mnt/c/workspace/andover-releasemanagement/node_modules/serverless-plugin-deploy-environment/src/index.js:4
import _ from 'lodash'
^^^^^^
```

**Comment by jacob-meacham** [comment]
I assume that you made the change specified by #6, but the code in src/ is ES2016 and so won't work without transpilation

**Comment by concon121** [comment]
Yes my thoughts exactly.  Not being a babbler, how does transpilation happen?

**Comment by jacob-meacham** [comment]
@concon121 I missed this notification - sorry! 1.0.3 should already have the transpiled code in lib/. If you want to build it yourself, you can do so with `npm run build`
